# Generated by Django 4.0.5 on 2022-07-30 13:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
