# Generated by Django 4.1.2 on 2023-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_profile_photo_alter_blog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
